apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.toml: |
    [sources.internal_metrics]
        type = "internal_metrics"

    [sinks.stdout]
        type = "console"
        inputs = ["kubernetes_logs", "internal_metrics"]
        target = "stdout"
        encoding = "json"
